# Generated by Django 4.1.2 on 2022-12-06 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(1, 'active'), (2, 'closed'), (3, 'unknown')])),
                ('styles', models.CharField(max_length=128)),
                ('founding_year', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
